
#pragma once

namespace quantdata {
namespace internal {

struct SSymbolPair
{
	const char* const symbol;
	const char* const name;
};

const char* const oandaSymbolSources[] =
{
	"https://api-fxtrade.oanda.com/v1/instruments",
};

const char* const alphaVantageSymbolSources[] =
{
	"https://www.alphavantage.co/digital_currency_list/",
	"https://www.alphavantage.co/physical_currency_list/",
};

const char* const openExchangeSymbolSources[] =
{
	"https://openexchangerates.org/api/currencies.json",
};

const SSymbolPair alphaVantageDigitalCurrencies[] =
{
	{"1ST","FirstBlood"},
	{"2GIVE","GiveCoin"},
	{"808","808Coin"},
	{"AC","AsiaCoin"},
	{"ACT","Achain"},
	{"ADA","Cardano"},
	{"ADK","Aidos-Kuneen"},
	{"ADL","Adelphoi"},
	{"ADT","adToken"},
	{"ADX","AdEx"},
	{"AE","Aeternity"},
	{"AEON","Aeon"},
	{"AGRS","IDNI-Agoras"},
	{"AMBER","AmberCoin"},
	{"AMP","Synereo"},
	{"ANC","Anoncoin"},
	{"ANS","NEO"},
	{"ANT","Aragon"},
	{"APX","APX-Ventures"},
	{"ARDR","Ardor"},
	{"ARK","Ark"},
	{"ATB","ATBCoin"},
	{"ATCC","ATC-Coin"},
	{"AUR","Auroracoin"},
	{"AVT","Aventus"},
	{"B3","B3Coin"},
	{"BAT","Basic-Attention-Token"},
	{"BAY","BitBay"},
	{"BCAP","BCAP"},
	{"BCC","BitConnect"},
	{"BCH","Bitcoin-Cash"},
	{"BCN","Bytecoin"},
	{"BCY","BitCrystals"},
	{"BDL","Bitdeal"},
	{"BELA","BelaCoin"},
	{"BET","DAO-Casino"},
	{"BIS","Bismuth"},
	{"BIT","First-Bitcoin"},
	{"BITB","BitBean"},
	{"BITBTC","BitBTC"},
	{"BITCNY","BitCNY"},
	{"BITEUR","BitEUR"},
	{"BITGBP","BitGBP"},
	{"BITOK","Bitok"},
	{"BITSILVER","BitSILVER"},
	{"BITUSD","BitUSD"},
	{"BLAS","BlakeStar"},
	{"BLK","Blackcoin"},
	{"BLN","Bolenum"},
	{"BLOCK","Blocknet"},
	{"BLOCKPAY","BlockPay"},
	{"BMC","Blackmoon-Crypto"},
	{"BNB","Binance-Coin"},
	{"BNT","Bancor-Network-Token"},
	{"BOST","BoostCoin"},
	{"BQ","bitqy"},
	{"BQX","Bitquence"},
	{"BTA","Bata"},
	{"BTC","Bitcoin"},
	{"BTCD","BitcoinDark"},
	{"BTM","Bitmark"},
	{"BTS","BitShares"},
	{"BTSR","BTSR"},
	{"BTX","Bitcore"},
	{"BURST","Burstcoin"},
	{"BUZZ","BuzzCoin"},
	{"BYC","Bytecent"},
	{"BYTOM","Bytom"},
	{"CANN","CannabisCoin"},
	{"CAT","BlockCAT"},
	{"CCRB","CryptoCarbon"},
	{"CDT","Coindash"},
	{"CFI","Cofound.it"},
	{"CHIPS","Chips"},
	{"CLAM","Clams"},
	{"CLOAK","CloakCoin"},
	{"CMP","Compcoin"},
	{"COSS","COSS"},
	{"COVAL","Circuits-Of-Value"},
	{"CRBIT","CreditBIT"},
	{"CREA","CreativeCoin"},
	{"CREDO","Credo"},
	{"CRW","Crown"},
	{"CTR","Centra"},
	{"CURE","CureCoin"},
	{"CVC","Civic"},
	{"DAR","Darcrus"},
	{"DASH","Dash"},
	{"DAY","Chronologic"},
	{"DCN","Dentacoin"},
	{"DCR","Decred"},
	{"DCT","DECENT"},
	{"DDF","Digital-Developers-Fund"},
	{"DENT","Dent"},
	{"DFS","DFSCoin"},
	{"DGB","DigiByte"},
	{"DGC","Digitalcoin"},
	{"DGD","DigixDAO"},
	{"DICE","Etheroll"},
	{"DNT","district0x"},
	{"DOGE","DogeCoin"},
	{"DOPE","DopeCoin"},
	{"DTB","Databits"},
	{"DYN","Dynamic"},
	{"EAC","EarthCoin"},
	{"EBST","eBoost"},
	{"EBTC","eBTC"},
	{"ECN","E-coin"},
	{"EDG","Edgeless"},
	{"ELIX","Elixir"},
	{"EMB","Embercoin"},
	{"EMC","Emercoin"},
	{"EMC2","Einsteinium"},
	{"EOS","EOS"},
	{"EOT","EOT-Token"},
	{"EQT","EquiTrader"},
	{"ETC","Ethereum-Classic"},
	{"ETH","Ethereum"},
	{"ETHD","Ethereum-Dark"},
	{"ETP","Metaverse-Entropy"},
	{"ETT","EncryptoTel"},
	{"EXP","Expanse"},
	{"FBC","Fibocoins"},
	{"FCT","Factom"},
	{"FID","BITFID"},
	{"FLDC","FoldingCoin"},
	{"FLO","FlorinCoin"},
	{"FLT","FlutterCoin"},
	{"FRST","FirstCoin"},
	{"FTC","Feathercoin"},
	{"FUN","FunFair"},
	{"GAM","Gambit"},
	{"GAME","GameCredits"},
	{"GAS","Gas"},
	{"GBG","Golos Gold"},
	{"GBYTE","Byteball"},
	{"GCR","GCRCoin"},
	{"GLD","GoldCoin"},
	{"GNO","Gnosis-Token"},
	{"GNT","Golem-Tokens"},
	{"GOLOS","Golos"},
	{"GRC","Gridcoin"},
	{"GRWI","Growers-International"},
	{"GUP","Guppy"},
	{"GXS","GXShares"},
	{"HBN","HoboNickels"},
	{"HEAT","HEAT"},
	{"HMQ","Humaniq"},
	{"HSR","Hshare"},
	{"HUSH","Hush"},
	{"HVN","Hive"},
	{"ICN","ICONOMI"},
	{"ICO","ICOCoin"},
	{"IFC","Infinitecoin"},
	{"IFT","investFeed"},
	{"INCNT","Incent"},
	{"IND","Indorse-Token"},
	{"INF","InfChain"},
	{"INPAY","InPay"},
	{"INXT","Internxt"},
	{"IOC","IOCoin"},
	{"ION","ION"},
	{"IOP","Internet-of-People"},
	{"IOT","IOTA"},
	{"IQT","Iquant-Chain"},
	{"IXC","iXcoin"},
	{"IXT","InsureX"},
	{"KEXCOIN","KexCoin"},
	{"KICK","KickCoin"},
	{"KIN","KIN"},
	{"KMD","Komodo"},
	{"KNC","Kyber-Network"},
	{"KORE","KoreCoin"},
	{"KRS","Krypstal"},
	{"LBC","LBRY-Credits"},
	{"LGD","Legends-Room"},
	{"LINDA","Linda"},
	{"LINK","ChainLink"},
	{"LKK","Lykke"},
	{"LMC","LoMoCoin"},
	{"LRC","Loopring"},
	{"LSK","Lisk"},
	{"LTC","Litecoin"},
	{"LUN","Lunyr"},
	{"MAGN","Magnetcoin"},
	{"MAID","MaidSafeCoin"},
	{"MANA","Decentraland"},
	{"MAX","Maxcoin"},
	{"MBRS","Embers"},
	{"MCAP","MCAP"},
	{"MCO","Monaco"},
	{"MDA","Moeda-Loyalty-Points"},
	{"MEC","Megacoin"},
	{"MEME","Memetic"},
	{"MGC","MergeCoin"},
	{"MGO","MobileGo"},
	{"MINEX","Minex"},
	{"MINT","Mintcoin"},
	{"MLN","Melon"},
	{"MNE","Minereum"},
	{"MONA","MonaCoin"},
	{"MRT","Miners-Reward-Token"},
	{"MSP","Mothership"},
	{"MTH","Monetha"},
	{"MUE","MonetaryUnit"},
	{"MUSIC","Musicoin"},
	{"MYB","MyBit-Token"},
	{"MYR","Myriadcoin"},
	{"MYST","Mysterium"},
	{"MZC","Mazacoin"},
	{"NAMO","Namocoin"},
	{"NAUT","NautilusCoin"},
	{"NAV","Nav-Coin"},
	{"NBT","NuBits"},
	{"NDAO","NeuroDAO"},
	{"NDC","NeverDie-Coin"},
	{"NEBL","Neblio"},
	{"NEOS","NeosCoin"},
	{"NET","Nimiq"},
	{"NLC2","NoLimitCoin"},
	{"NLG","Gulden"},
	{"NMC","Namecoin"},
	{"NMR","Numeraire"},
	{"NOBL","NobleCoin"},
	{"NOTE","DNotes"},
	{"NSR","NuShares"},
	{"NTO","Fujinto"},
	{"NVC","Novacoin"},
	{"NXC","Nexium"},
	{"NXS","Nexus"},
	{"NXT","Nxt"},
	{"OAX","openANX"},
	{"OBITS","Obits"},
	{"OCL","Oceanlab"},
	{"ODN","Obsidian"},
	{"OK","OKCash"},
	{"OMG","OmiseGo"},
	{"OMNI","Omni"},
	{"ONION","DeepOnion"},
	{"OPT","Opus"},
	{"PART","Particl"},
	{"PASC","PascalCoin"},
	{"PAY","TenX"},
	{"PBT","Primalbase-Token"},
	{"PING","CryptoPing"},
	{"PINK","Pinkcoin"},
	{"PIVX","PIVX"},
	{"PIX","Lampix"},
	{"PLBT","Polybius"},
	{"PLR","Pillar"},
	{"PLU","Pluton"},
	{"POE","Poet"},
	{"POSW","PoSW-Coin"},
	{"POT","PotCoin"},
	{"PPC","Peercoin"},
	{"PPT","Populous"},
	{"PPY","Peerplays"},
	{"PRO","Propy"},
	{"PST","Primas"},
	{"PTC","Pesetacoin"},
	{"PTOY","Patientory"},
	{"PURA","Pura"},
	{"QAU","Quantum"},
	{"QRK","Quark"},
	{"QRL","Quantum-Resistant-Ledger"},
	{"QTL","Quatloo"},
	{"QTUM","Qtum"},
	{"QWARK","Qwark"},
	{"RADS","Radium"},
	{"RAIN","Condensate"},
	{"RBIES","Rubies"},
	{"RBX","Ripto-Bux"},
	{"RBY","RubyCoin"},
	{"RDD","ReddCoin"},
	{"REC","Regalcoin"},
	{"RED","Redcoin"},
	{"REP","Augur"},
	{"RIC","Riecoin"},
	{"RISE","Rise"},
	{"RLC","RLC-Token"},
	{"RLT","RouletteToken"},
	{"ROUND","Round"},
	{"RRT","Recovery-Right-Tokens"},
	{"RUP","Rupee"},
	{"RVT","Rivetz"},
	{"SALT","Salt"},
	{"SAN","Santiment-Network-Token"},
	{"SBD","Steem-Dollars"},
	{"SC","Siacoin"},
	{"SDC","ShadowCash"},
	{"SEC","SafeExchangeCoin"},
	{"SEQ","Sequence"},
	{"SHIFT","SHIFT"},
	{"SIGMA","SIGMAcoin"},
	{"SIGT","Signatum"},
	{"SJCX","Storjcoin-X"},
	{"SKIN","SkinCoin"},
	{"SKY","Skycoin"},
	{"SLS","SaluS"},
	{"SMART","SmartCash"},
	{"SNC","SunContract"},
	{"SNGLS","SingularDTV"},
	{"SNM","SONM"},
	{"SNRG","Synergy"},
	{"SNT","Status-Network-Token"},
	{"SPR","SpreadCoin"},
	{"START","Startcoin"},
	{"STEEM","Steem"},
	{"STORJ","Storj"},
	{"STRAT","Stratis"},
	{"STRC","StarCredits"},
	{"STX","Stox"},
	{"SUB","Substratum"},
	{"SWT","Swarm-City"},
	{"SYS","SysCoin"},
	{"TAAS","Taas"},
	{"TCC","The-ChampCoin"},
	{"TFL","True-Flip"},
	{"TIME","Time"},
	{"TIX","Blocktix"},
	{"TKN","TokenCard"},
	{"TKR","Trackr"},
	{"TKS","Tokes"},
	{"TNT","Tierion"},
	{"TOA","ToaCoin"},
	{"TRC","Terracoin"},
	{"TRIG","Triggers"},
	{"TRST","Trustcoin"},
	{"TRX","Tronix"},
	{"UBQ","Ubiq"},
	{"ULA","Ulatech"},
	{"UNITY","SuperNET"},
	{"UNO","Unobtanium"},
	{"UNY","Unity-Ingot"},
	{"URO","Uro"},
	{"USDT","Tether"},
	{"VEN","VeChain"},
	{"VERI","Veritaseum"},
	{"VIA","Viacoin"},
	{"VIB","Viberate"},
	{"VIVO","VIVO"},
	{"VOISE","Voise"},
	{"VOX","Voxels"},
	{"VPN","VPNCoin"},
	{"VRC","Vericoin"},
	{"VRM","Verium"},
	{"VRS","Veros"},
	{"VSL","vSlice"},
	{"VTC","Vertcoin"},
	{"VTR","vTorrent"},
	{"WAVES","Waves"},
	{"WCT","Waves-Community"},
	{"WDC","WorldCoin"},
	{"WGO","WavesGo"},
	{"WGR","Wagerr"},
	{"WINGS","Wings"},
	{"WTC","Walton"},
	{"WTT","Giga-Watt-Token"},
	{"XAS","Asch"},
	{"XAUR","Xaurum"},
	{"XBC","Bitcoin-Plus"},
	{"XBY","XtraBYtes"},
	{"XCN","Cryptonite"},
	{"XCP","Counterparty"},
	{"XDN","DigitalNote"},
	{"XEL","Elastic"},
	{"XEM","NEM"},
	{"XID","Air"},
	{"XLM","Stellar"},
	{"XMR","Monero"},
	{"XMT","Metal"},
	{"XPM","Primecoin"},
	{"XPY","PayCoin"},
	{"XRB","RaiBlocks"},
	{"XRL","Rialto"},
	{"XRP","Ripples"},
	{"XSPEC","Spectrecoin"},
	{"XST","Stealthcoin"},
	{"XTZ","Tezos"},
	{"XVC","Vcash"},
	{"XVG","Verge"},
	{"XWC","WhiteCoin"},
	{"XZC","ZCoin"},
	{"XZR","ZrCoin"},
	{"YBC","YbCoin"},
	{"YOYOW","YOYOW"},
	{"ZCC","ZcCoin"},
	{"ZCL","Zclassic"},
	{"ZEC","Zcash"},
	{"ZEN","ZenCash"},
	{"ZET","Zetacoin"},
	{"ZRX","0x"},
};

const SSymbolPair alphaVantagePhysicalCurrencies[] =
{
	{"AED","United Arab Emirates Dirham"},
	{"AFN","Afghan Afghani"},
	{"ALL","Albanian Lek"},
	{"AMD","Armenian Dram"},
	{"ANG","Netherlands Antillean Guilder"},
	{"AOA","Angolan Kwanza"},
	{"ARS","Argentine Peso"},
	{"AUD","Australian Dollar"},
	{"AWG","Aruban Florin"},
	{"AZN","Azerbaijani Manat"},
	{"BAM","Bosnia-Herzegovina Convertible Mark"},
	{"BBD","Barbadian Dollar"},
	{"BDT","Bangladeshi Taka"},
	{"BGN","Bulgarian Lev"},
	{"BHD","Bahraini Dinar"},
	{"BIF","Burundian Franc"},
	{"BITGOLD","BitGOLD"},
	{"BMD","Bermudan Dollar"},
	{"BND","Brunei Dollar"},
	{"BOB","Bolivian Boliviano"},
	{"BRL","Brazilian Real"},
	{"BSD","Bahamian Dollar"},
	{"BTN","Bhutanese Ngultrum"},
	{"BWP","Botswanan Pula"},
	{"BYR","Belarusian Ruble (pre-2016)"},
	{"BZD","Belize Dollar"},
	{"CAD","Canadian Dollar"},
	{"CDF","Congolese Franc"},
	{"CHF","Swiss Franc"},
	{"CLF","Chilean Unit of Account (UF)"},
	{"CLP","Chilean Peso"},
	{"CNY","Chinese Yuan"},
	{"COP","Colombian Peso"},
	{"CRC","Costa Rican Colon"},
	{"CUP","Cuban Peso"},
	{"CVE","Cape Verdean Escudo"},
	{"CZK","Czech Republic Koruna"},
	{"DJF","Djiboutian Franc"},
	{"DKK","Danish Krone"},
	{"DOP","Dominican Peso"},
	{"DZD","Algerian Dinar"},
	{"EEK","Estonian Kroon"},
	{"EGP","Egyptian Pound"},
	{"ERN","Eritrean Nakfa"},
	{"ETB","Ethiopian Birr"},
	{"EUR","Euro"},
	{"FJD","Fijian Dollar"},
	{"FKP","Falkland Islands Pound"},
	{"GBP","British Pound Sterling"},
	{"GEL","Georgian Lari"},
	{"GHS","Ghanaian Cedi"},
	{"GIP","Gibraltar Pound"},
	{"GMD","Gambian Dalasi"},
	{"GNF","Guinean Franc"},
	{"GTQ","Guatemalan Quetzal"},
	{"GYD","Guyanaese Dollar"},
	{"HKD","Hong Kong Dollar"},
	{"HNL","Honduran Lempira"},
	{"HRK","Croatian Kuna"},
	{"HTG","Haitian Gourde"},
	{"HUF","Hungarian Forint"},
	{"IDR","Indonesian Rupiah"},
	{"ILS","Israeli New Sheqel"},
	{"INR","Indian Rupee"},
	{"IQD","Iraqi Dinar"},
	{"IRR","Iranian Rial"},
	{"ISK","Icelandic Krona"},
	{"JEP","Jersey Pound"},
	{"JMD","Jamaican Dollar"},
	{"JOD","Jordanian Dinar"},
	{"JPY","Japanese Yen"},
	{"KES","Kenyan Shilling"},
	{"KGS","Kyrgystani Som"},
	{"KHR","Cambodian Riel"},
	{"KMF","Comorian Franc"},
	{"KPW","North Korean Won"},
	{"KRW","South Korean Won"},
	{"KWD","Kuwaiti Dinar"},
	{"KYD","Cayman Islands Dollar"},
	{"KZT","Kazakhstani Tenge"},
	{"LAK","Laotian Kip"},
	{"LBP","Lebanese Pound"},
	{"LKR","Sri Lankan Rupee"},
	{"LRD","Liberian Dollar"},
	{"LSL","Lesotho Loti"},
	{"LTL","Lithuanian Litas"},
	{"LVL","Latvian Lats"},
	{"LYD","Libyan Dinar"},
	{"MAD","Moroccan Dirham"},
	{"MDL","Moldovan Leu"},
	{"MGA","Malagasy Ariary"},
	{"MKD","Macedonian Denar"},
	{"MMK","Myanma Kyat"},
	{"MNT","Mongolian Tugrik"},
	{"MOP","Macanese Pataca"},
	{"MRO","Mauritanian Ouguiya"},
	{"MTL","Maltese Lira"},
	{"MUR","Mauritian Rupee"},
	{"MVR","Maldivian Rufiyaa"},
	{"MWK","Malawian Kwacha"},
	{"MXN","Mexican Peso"},
	{"MYRf","Malaysian Ringgit"},
	{"MZN","Mozambican Metical"},
	{"NAD","Namibian Dollar"},
	{"NGN","Nigerian Naira"},
	{"NIO","Nicaraguan Cordoba"},
	{"NOK","Norwegian Krone"},
	{"NPR","Nepalese Rupee"},
	{"NZD","New Zealand Dollar"},
	{"OMR","Omani Rial"},
	{"PAB","Panamanian Balboa"},
	{"PEN","Peruvian Nuevo Sol"},
	{"PGK","Papua New Guinean Kina"},
	{"PHP","Philippine Peso"},
	{"PKR","Pakistani Rupee"},
	{"PLN","Polish Zloty"},
	{"PYG","Paraguayan Guarani"},
	{"QAR","Qatari Rial"},
	{"RON","Romanian Leu"},
	{"RSD","Serbian Dinar"},
	{"RUB","Russian Ruble"},
	{"RUR","Old Russian Ruble"},
	{"RWF","Rwandan Franc"},
	{"SAR","Saudi Riyal"},
	{"SBDf","Solomon Islands Dollar"},
	{"SCR","Seychellois Rupee"},
	{"SDG","Sudanese Pound"},
	{"SEK","Swedish Krona"},
	{"SGD","Singapore Dollar"},
	{"SHP","Saint Helena Pound"},
	{"SLL","Sierra Leonean Leone"},
	{"SOS","Somali Shilling"},
	{"SRD","Surinamese Dollar"},
	{"STD","Sao Tome and Principe Dobra"},
	{"SVC","Salvadoran Colon"},
	{"SYP","Syrian Pound"},
	{"SZL","Swazi Lilangeni"},
	{"THB","Thai Baht"},
	{"TJS","Tajikistani Somoni"},
	{"TMT","Turkmenistani Manat"},
	{"TND","Tunisian Dinar"},
	{"TOP","Tongan Pa'anga"},
	{"TRY","Turkish Lira"},
	{"TTD","Trinidad and Tobago Dollar"},
	{"TWD","New Taiwan Dollar"},
	{"TZS","Tanzanian Shilling"},
	{"UAH","Ukrainian Hryvnia"},
	{"UGX","Ugandan Shilling"},
	{"USD","United States Dollar"},
	{"USDE","USDe"},
	{"UYU","Uruguayan Peso"},
	{"UZS","Uzbekistan Som"},
	{"VEF","Venezuelan Bolivar Fuerte"},
	{"VND","Vietnamese Dong"},
	{"VUV","Vanuatu Vatu"},
	{"WST","Samoan Tala"},
	{"XAF","CFA Franc BEAC"},
	{"XAG","Silver Ounce"},
	{"XAU","Gold Ounce"},
	{"XCD","East Caribbean Dollar"},
	{"XDR","Special Drawing Rights"},
	{"XOF","CFA Franc BCEAO"},
	{"XPF","CFP Franc"},
	{"YER","Yemeni Rial"},
	{"ZAR","South African Rand"},
	{"ZMK","Zambian Kwacha (pre-2013)"},
	{"ZMW","Zambian Kwacha"},
	{"ZWL","Zimbabwean Dollar"},
};

const SSymbolPair openExchangeSymbols[] =
{
	{"AED", "United Arab Emirates Dirham"},
	{"AFN", "Afghan Afghani"},
	{"ALL", "Albanian Lek"},
	{"AMD", "Armenian Dram"},
	{"ANG", "Netherlands Antillean Guilder"},
	{"AOA", "Angolan Kwanza"},
	{"ARS", "Argentine Peso"},
	{"AUD", "Australian Dollar"},
	{"AWG", "Aruban Florin"},
	{"AZN", "Azerbaijani Manat"},
	{"BAM", "Bosnia-Herzegovina Convertible Mark"},
	{"BBD", "Barbadian Dollar"},
	{"BDT", "Bangladeshi Taka"},
	{"BGN", "Bulgarian Lev"},
	{"BHD", "Bahraini Dinar"},
	{"BIF", "Burundian Franc"},
	{"BMD", "Bermudan Dollar"},
	{"BND", "Brunei Dollar"},
	{"BOB", "Bolivian Boliviano"},
	{"BRL", "Brazilian Real"},
	{"BSD", "Bahamian Dollar"},
	{"BTC", "Bitcoin"},
	{"BTN", "Bhutanese Ngultrum"},
	{"BWP", "Botswanan Pula"},
	{"BYN", "Belarusian Ruble"},
	{"BZD", "Belize Dollar"},
	{"CAD", "Canadian Dollar"},
	{"CDF", "Congolese Franc"},
	{"CHF", "Swiss Franc"},
	{"CLF", "Chilean Unit of Account (UF)"},
	{"CLP", "Chilean Peso"},
	{"CNH", "Chinese Yuan (Offshore)"},
	{"CNY", "Chinese Yuan"},
	{"COP", "Colombian Peso"},
	{"CRC", "Costa Rican Colón"},
	{"CUC", "Cuban Convertible Peso"},
	{"CUP", "Cuban Peso"},
	{"CVE", "Cape Verdean Escudo"},
	{"CZK", "Czech Republic Koruna"},
	{"DJF", "Djiboutian Franc"},
	{"DKK", "Danish Krone"},
	{"DOP", "Dominican Peso"},
	{"DZD", "Algerian Dinar"},
	{"EGP", "Egyptian Pound"},
	{"ERN", "Eritrean Nakfa"},
	{"ETB", "Ethiopian Birr"},
	{"EUR", "Euro"},
	{"FJD", "Fijian Dollar"},
	{"FKP", "Falkland Islands Pound"},
	{"GBP", "British Pound Sterling"},
	{"GEL", "Georgian Lari"},
	{"GGP", "Guernsey Pound"},
	{"GHS", "Ghanaian Cedi"},
	{"GIP", "Gibraltar Pound"},
	{"GMD", "Gambian Dalasi"},
	{"GNF", "Guinean Franc"},
	{"GTQ", "Guatemalan Quetzal"},
	{"GYD", "Guyanaese Dollar"},
	{"HKD", "Hong Kong Dollar"},
	{"HNL", "Honduran Lempira"},
	{"HRK", "Croatian Kuna"},
	{"HTG", "Haitian Gourde"},
	{"HUF", "Hungarian Forint"},
	{"IDR", "Indonesian Rupiah"},
	{"ILS", "Israeli New Sheqel"},
	{"IMP", "Manx pound"},
	{"INR", "Indian Rupee"},
	{"IQD", "Iraqi Dinar"},
	{"IRR", "Iranian Rial"},
	{"ISK", "Icelandic Króna"},
	{"JEP", "Jersey Pound"},
	{"JMD", "Jamaican Dollar"},
	{"JOD", "Jordanian Dinar"},
	{"JPY", "Japanese Yen"},
	{"KES", "Kenyan Shilling"},
	{"KGS", "Kyrgystani Som"},
	{"KHR", "Cambodian Riel"},
	{"KMF", "Comorian Franc"},
	{"KPW", "North Korean Won"},
	{"KRW", "South Korean Won"},
	{"KWD", "Kuwaiti Dinar"},
	{"KYD", "Cayman Islands Dollar"},
	{"KZT", "Kazakhstani Tenge"},
	{"LAK", "Laotian Kip"},
	{"LBP", "Lebanese Pound"},
	{"LKR", "Sri Lankan Rupee"},
	{"LRD", "Liberian Dollar"},
	{"LSL", "Lesotho Loti"},
	{"LYD", "Libyan Dinar"},
	{"MAD", "Moroccan Dirham"},
	{"MDL", "Moldovan Leu"},
	{"MGA", "Malagasy Ariary"},
	{"MKD", "Macedonian Denar"},
	{"MMK", "Myanma Kyat"},
	{"MNT", "Mongolian Tugrik"},
	{"MOP", "Macanese Pataca"},
	{"MRO", "Mauritanian Ouguiya"},
	{"MUR", "Mauritian Rupee"},
	{"MVR", "Maldivian Rufiyaa"},
	{"MWK", "Malawian Kwacha"},
	{"MXN", "Mexican Peso"},
	{"MYR", "Malaysian Ringgit"},
	{"MZN", "Mozambican Metical"},
	{"NAD", "Namibian Dollar"},
	{"NGN", "Nigerian Naira"},
	{"NIO", "Nicaraguan Córdoba"},
	{"NOK", "Norwegian Krone"},
	{"NPR", "Nepalese Rupee"},
	{"NZD", "New Zealand Dollar"},
	{"OMR", "Omani Rial"},
	{"PAB", "Panamanian Balboa"},
	{"PEN", "Peruvian Nuevo Sol"},
	{"PGK", "Papua New Guinean Kina"},
	{"PHP", "Philippine Peso"},
	{"PKR", "Pakistani Rupee"},
	{"PLN", "Polish Zloty"},
	{"PYG", "Paraguayan Guarani"},
	{"QAR", "Qatari Rial"},
	{"RON", "Romanian Leu"},
	{"RSD", "Serbian Dinar"},
	{"RUB", "Russian Ruble"},
	{"RWF", "Rwandan Franc"},
	{"SAR", "Saudi Riyal"},
	{"SBD", "Solomon Islands Dollar"},
	{"SCR", "Seychellois Rupee"},
	{"SDG", "Sudanese Pound"},
	{"SEK", "Swedish Krona"},
	{"SGD", "Singapore Dollar"},
	{"SHP", "Saint Helena Pound"},
	{"SLL", "Sierra Leonean Leone"},
	{"SOS", "Somali Shilling"},
	{"SRD", "Surinamese Dollar"},
	{"SSP", "South Sudanese Pound"},
	{"STD", "São Tomé and Príncipe Dobra"},
	{"SVC", "Salvadoran Colón"},
	{"SYP", "Syrian Pound"},
	{"SZL", "Swazi Lilangeni"},
	{"THB", "Thai Baht"},
	{"TJS", "Tajikistani Somoni"},
	{"TMT", "Turkmenistani Manat"},
	{"TND", "Tunisian Dinar"},
	{"TOP", "Tongan Pa'anga"},
	{"TRY", "Turkish Lira"},
	{"TTD", "Trinidad and Tobago Dollar"},
	{"TWD", "New Taiwan Dollar"},
	{"TZS", "Tanzanian Shilling"},
	{"UAH", "Ukrainian Hryvnia"},
	{"UGX", "Ugandan Shilling"},
	{"USD", "United States Dollar"},
	{"UYU", "Uruguayan Peso"},
	{"UZS", "Uzbekistan Som"},
	{"VEF", "Venezuelan Bolívar Fuerte"},
	{"VND", "Vietnamese Dong"},
	{"VUV", "Vanuatu Vatu"},
	{"WST", "Samoan Tala"},
	{"XAF", "CFA Franc BEAC"},
	{"XAG", "Silver Ounce"},
	{"XAU", "Gold Ounce"},
	{"XCD", "East Caribbean Dollar"},
	{"XDR", "Special Drawing Rights"},
	{"XOF", "CFA Franc BCEAO"},
	{"XPD", "Palladium Ounce"},
	{"XPF", "CFP Franc"},
	{"XPT", "Platinum Ounce"},
	{"YER", "Yemeni Rial"},
	{"ZAR", "South African Rand"},
	{"ZMW", "Zambian Kwacha"},
	{"ZWL", "Zimbabwean Dollar"},
};

const SSymbolPair trueFxSymbols[] =
{
	{"EUR/USD", ""},
	{"USD/JPY", ""},
	{"GBP/USD", ""},
	{"EUR/GBP", ""},
	{"CAD/CHF", ""},
	{"CAD/JPY", ""},
	{"CHF/JPY", ""},
	{"EUR/AUD", ""},
	{"USD/CHF", ""},
	{"EUR/JPY", ""},
	{"EUR/CHF", ""},
	{"USD/CAD", ""},
	{"AUD/USD", ""},
	{"GBP/JPY", ""},
	{"AUD/CAD", ""},
	{"AUD/CHF", ""},
	{"AUD/JPY", ""},
	{"AUD/NZD", ""},
	{"EUR/CAD", ""},
	{"EUR/NOK", ""},
	{"EUR/NZD", ""},
	{"GBP/CAD", ""},
	{"GBP/CHF", ""},
	{"NZD/JPY", ""},
	{"NZD/USD", ""},
	{"USD/NOK", ""},
	{"USD/SEK", ""},
};

} // namespace internal
} // namespace quantdata
